### ISSUE TITLE
leite.pessoa.cpf is not a function

### ISSUE THREAD

**Issue by RotcivOcnarb** [idwall/leite#2]
Só pra avisar, não se se perceberam, mas o pacote do npm, não existe a função "cpf" no objeto "leite.pessoa"

Objeto usando `console.log(leite)`

[https://i.imgur.com/dtw3gRo.png](url)

**Comment by WoLfulus** [comment]
@bukinoshita não fizemos o release depois do seu PR monstrão?

edit: nevermind, foi publicado sim... vou dar uma olhada.

**Comment by christiansaiki** [comment]
@WoLfulus eu corrigi esse comportamento, da uma olhada no meu PR por favor?

**Comment by WoLfulus** [comment]
Pessoal, desculpa a demora! 

@christiansaiki não estou mais trabalhando na ID então não consigo fazer o merge. :(

**Comment by WoLfulus** [comment]
Pessoal, desculpa a demora.

Como não estou trabalhando mais na ID, não consigo fazer o merge mais.

@raphaelgmelo e @bukinoshita, conseguem fazer um review no PR?

**Comment by marcelorl** [comment]
seria bem legal aprovar esse Przinho....pra mim parece bem ok.

**Comment by froquede** [comment]
Pessoal, a module npm a princípio não foi atualizada com essa última versão, instalando por lá ainda não tem o cpf no objeto pessoa.

**Comment by ericreis** [comment]
alguma previsão de quando vai ser atualizado no npm?

**Comment by WoLfulus** [comment]
@roquef @ericreis subi como leite@0.2.0
