### ISSUE TITLE
Gerar CEP válido baseado no estado

### ISSUE THREAD

**Issue by marcelorl** [idwall/leite#7]
esse TO-DO

o CEP teria que ser realmente válido ou não?

eu consigo fazer CEP por estado e colocando uma outra opção para o metodo de CEP:

`leite.localizacao.cep({ estado: 'rn' })`

mas para garantir que é valido teria que bater na API dos correios. hoje o metodo não garante que o cep é valido, porque gera numeros aleatórios.

existe a necessidade de ser um cep verdadeiro?

o que voces acham?

**Comment by bukinoshita** [comment]
Acho que poderiamos gerar o CEP por estado sem ser "verdadeiro", e depois fazemos esse improvement. O que acha?

**Comment by marcelorl** [comment]
eu acho justo...

o farei então.
